<?php

namespace Database\Seeders;

use App\Models\Wilayah;
use Illuminate\Database\Seeder;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'SUMBEROTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'PURWOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'MENTARAMAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'DONOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'TEMPURSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'TLOGOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'KEDUNGSALAM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'BANJARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'TULUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DONOMULYO', 'kelurahan' => 'PURWODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'ARJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'TUMPAKREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'KALIASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'PUTUKREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'KALIPARE']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'SUKOWILANGUN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'ARJOWILANGUN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KALIPARE', 'kelurahan' => 'KALIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'SUMBERMANJING KULON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'PANDANREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'SUMBERKERTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'SEMPOL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'PAGAK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'SUMBERREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'GAMPINGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGAK', 'kelurahan' => 'TLOGOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'BANDUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'SUMBERBENING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'SRIGONCO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'WONOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'BANTUR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'PRINGGODANI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'REJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'WONOKERTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'REJOYOSO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BANTUR', 'kelurahan' => 'KARANGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'TUMPAKREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'SINDUREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'GAJAHREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'SIDODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'GEDANGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'SEGARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'SUMBEREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GEDANGAN', 'kelurahan' => 'GIRIMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'SITIARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'TAMBAKREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'KEDUNGBANTENG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'TAMBAKASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'TEGALREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'RINGINKEMBAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'SUMBERAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'HARJOKUNCARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'ARGOTIRTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'RINGINSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'SUMBERMANJING WETAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'SEKARBANYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBERMANJING', 'kelurahan' => 'SIDOASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'SUKODONO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'SRIMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'BATURETNO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'BUMIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'SUMBERSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'AMADANOM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'DAMPIT']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'PAMOTAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'MAJANGTENGAH']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'POJOK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAMPIT', 'kelurahan' => 'JAMBANGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'PURWODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'PUJIHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'SUMBERTANGKIL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'KEPATIHAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'JOGOMULYAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'TIRTOYUDO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'GADUNGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'TLOGOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'SUKOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'AMPELGADING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'TAMANKUNCARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'WONOAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TIRTO YUDO', 'kelurahan' => 'TAMANSATRIYAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'LEBAKHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'WIROTAMAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'TAMANASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'SONOWANGI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'TIRTOMARTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'PURWOHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'SIDORENGGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'TIRTOMOYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'TAWANGAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'SIMOJAYAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'ARGOYUWONO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'MULYOASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'AMPELGADING', 'kelurahan' => 'TAMANSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'DAWUHAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'SUMBEREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'PANDANSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'NGADIRESO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'KARANGANYAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'JAMBESARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'PAJARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'ARGOSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'KARANGNONGKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'WONOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'WONOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'PONCOKUSUMO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'WRINGINANOM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'GUBUKKLAKAH']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PONCOKUSUMO', 'kelurahan' => 'NGADAS']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'SUMBERPUTIH']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'WONOAYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'BAMBANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'BRINGIN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'DADAPAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'PATOKPICIS']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'BLAYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'CODO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'SUKOLILO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'KIDANGBANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'SUKOANYAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'WAJAK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAJAK', 'kelurahan' => 'NGEMBAL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'KEMULAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'TAWANGREJENI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'SAWAHAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'UNDAAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'GEDOG KULON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'GEDOG WETAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'TALOK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'SEDAYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'TANGGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'PAGEDANGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'SANANKERTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'SANANREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'KEDOK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUREN', 'kelurahan' => 'TALANGSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'SUKONOLO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'GADING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'BAKALAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'SUDIMORO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'KASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'PRINGU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'KASEMBON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'KUWOLU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'KREBET  SENGGRONG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'LUMBANGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'WANDANPURO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'BULULAWANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BULULAWANG', 'kelurahan' => 'SEMPALWADAK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'SUKOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'BULUPITU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'SUKOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'PANGGUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'GONDANGLEGI KULON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'GONDANGLEGI WETAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'SEPANJANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'PUTAT KIDUL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'PUTAT LOR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'KETAWANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'GANJARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'PUTUKREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'GONDANGLEGI', 'kelurahan' => 'SUMBERJAYA']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'KANIGORO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'BALEARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'KADEMANGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'SUWARU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'CLUMPRIT']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'SIDOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'PAGELARAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'BANJAREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'BRONGKAL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAGELARAN', 'kelurahan' => 'KARANGSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'JENGGOLO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'KEMIRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'TEGALSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'MANGUNREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'PANGGUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'KEDUNGPEDARINGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'PENARUKAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'CEPOKOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'KEPANJEN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'TALANGAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'DILEM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'ARDIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'SUKORAHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'CURUNG REJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'JATIREJOYOSO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'NGADILANGKUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEPANJEN', 'kelurahan' => 'MOJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'KARANGKATES']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'JATIGUWI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'SAMBIGEDE']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'TERNYANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'SLOROK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'JATIKERTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'NGADIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'KARANGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'KROMENGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'PENIWEN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KROMENGAN', 'kelurahan' => 'JAMBUWER']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'NGAJUM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'PALAAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'NGASEM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'BANJARSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'KRANGGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'KESAMBEN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'BABADAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'BALESARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGAJUM', 'kelurahan' => 'MAGUAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WONOSARI', 'kelurahan' => 'PLANDI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WONOSARI', 'kelurahan' => 'PLAOSAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WONOSARI', 'kelurahan' => 'KEBOBANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WONOSARI', 'kelurahan' => 'BANGELAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WONOSARI', 'kelurahan' => 'WONOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'SUMBERSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'MENDALANWANGI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'SITIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'PARANGARGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'GONDOWANGI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'PANDANREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'SUKODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'SIDORAHAYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'JEDONG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'DALISODO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'WAGIR', 'kelurahan' => 'PANDANLANDUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'PERMANU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'KARANGPANDAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'GLANGGANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'SUTOJAYAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'WONOKERSO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'KARANGDUREN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'PAKISAJI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'JATISARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'WADUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'GENENGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'KEBONAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKISAJI', 'kelurahan' => 'KENDALPAYAK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'TAMBAKASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'TANGKILSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'JAMBEARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'JATISARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'PANDANMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'NGAWONGGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'PURWOSEKAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'GUNUNGRONGGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'GUNUNGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'TAJINAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'RANDUGADING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TAJINAN', 'kelurahan' => 'SUMBERSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'NGINGIT']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'KIDAL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'KAMBINGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'PANDANAJENG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'PULUNGDOWO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'BOKOR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'SLAMET']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'WRINGINSONGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'MALANGSUKO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'TUMPANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'TULUSBESAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'BENJOR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'TUMPANG', 'kelurahan' => 'DUWET KRAJAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'SEKARPURO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'AMPELDENTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'SUMBERKRADENAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'KEDUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'BANJARREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'PUCANG SONGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'SUKOANYAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'SUMBERPASIR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'PAKISKEMBAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'PAKISJAJAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'BUNUTWETAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'ASRIKATON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'SAPTORENGGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'MANGLIAWAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PAKIS', 'kelurahan' => 'TIRTOMOYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'KENONGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'NGADIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'TAJI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'PANDANSARI LOR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'SUKOPURO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'SIDOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'SUKOLILO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'SIDOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'GADING KEMBAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'KEMANTREN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'ARGOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'SLAMPAREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'KEMIRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'JABUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'JABUNG', 'kelurahan' => 'GUNUNG JATI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'SIDOLUHUR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'SRIGADING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'SIDODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'BEDALI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'KALIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'MULYOARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'SUMBER NGEPOH']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'SUMBER PORONG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'TURIREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'LAWANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'KETINDAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LAWANG', 'kelurahan' => 'WONOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'LANGLANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'TUNJUNGTIRTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'BANJARARUM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'WATUGEDE']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'DENGKOL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'WONOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'BATURETNO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'TAMANHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'LOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'PAGENTAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'PURWOASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'KLAMPOK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'GUNUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'CANDIRENGGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'ARDIMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'RANDUAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SINGOSARI', 'kelurahan' => 'TOYOMARTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'TEGALGONDO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'KEPUHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'NGIJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'AMPELDENTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'GIRIMOYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'BOCEK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'DONOWARIH']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KARANGPLOSO', 'kelurahan' => 'TAWANGARGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'KALISONGO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'KARANGWIDORO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'SELOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'TEGALWERU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'LANDUNGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'GADINGKULON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'MULYOAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'DAU', 'kelurahan' => 'SUMBERSEKAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'BENDOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'SUKOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'PUJON KIDUL']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'PANDESARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'PUJON LOR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'NGROTO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'NGABAB']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'TAWANGSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'MADIREDO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'PUJON', 'kelurahan' => 'WIYUREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'PAGERSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'SIDODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'BANJAREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'PURWOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'NGANTRU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'BANTUREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'PANDANSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'MULYOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'SUMBERAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'KAUMREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'TULUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'WATUREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'NGANTANG', 'kelurahan' => 'JOMBOK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'PONDOK AGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'BAYEM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'PAIT']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'WONOAGUNG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'KASEMBON']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KASEMBON', 'kelurahan' => 'SUKOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'ARJOWINANGUN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'TLOGOWARU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'WONOKOYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'BUMIAYU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'BURING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'MERGOSONO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'KOTALAMA']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'KEDUNGKANDANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'SAWOJAJAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'MADYOPURO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'LESANPURO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KEDUNGKANDANG', 'kelurahan' => 'CEMOROKANDANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'KEBONSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'GADANG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'CIPTOMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'BANDUNGREJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'BAKALAN KRAJAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'MULYOREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'BANDULAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'TANJUNGREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'PISANG CANDI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUKUN', 'kelurahan' => 'KARANG BESUKI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'KASIN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'SUKOHARJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'KIDUL DALEM']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'KAUMAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'BARENG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'GADINGKASRI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'ORO ORO DOWO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'KLOJEN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'RAMPAL CELAKET']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'SAMAAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'KLOJEN', 'kelurahan' => 'PENANGGUNGAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'JODIPAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'POLEHAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'KESATRIAN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'BUNULREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'PURWANTORO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'PANDANWANGI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'BLIMBING']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'PURWODADI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'POLOWIJEN']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'ARJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'BLIMBING', 'kelurahan' => 'BALEARJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'MERJOSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'DINOYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'SUMBERSARI']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'KETAWANGGEDE']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'JATIMULYO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'LOWOKWARU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'TULUSREJO']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'MOJOLANGU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'TUNJUNGSEKAR']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'TASIKMADU']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'LOWOKWARU', 'kelurahan' => 'TLOGOMAS']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'SENGGRENG']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'NGEBRUK']);
        Wilayah::create(['kabupaten' => 'Malang', 'kecamatan' => 'SUMBER PUCUNG', 'kelurahan' => 'SUMBERPUCUNG']);
    }
}
